### ISSUE TITLE
Error: cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by martsper** [JuliaHelmecke/metano#1]
Dear Metano developers,

I have trouble to get Metano running, maybe you have an idea for how to fix it.

I installed metano in a conda base environment (python 3.8.12; conda 4.11.0).

When running fba.py, or any other script, I get the following:
ImportError: cannot import name 'clock' from 'time' (unknown location)

(specifically, I would like to run sbmlwriter.py, which is currently not implemented in the metano webpage).

Best,

Martin

**Comment by martsper** [comment]
Hi again,

we made several attempts to install metano under different python versions. Our aim was to convert your metabolic model of Phaeobacter into a SBML file. The closest we came to get it running was with using a conda environment, and the following definitions:

name:
 - metano

channels:
  - conda-forge
  - defaults

dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_1
  - cvxopt=1.2.0=py37hfa32c7d_0
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - gsl=2.4=h14c3975_4
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - metis=5.1.0=h58526e2_1006
  - mkl=2020.2=256
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - python_abi=3.7=2_cp37m
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py37h06a4308_0
  - sqlite=3.37.0=hc218d9a_0
  - suitesparse=5.2.0=h9e4a6bb_0
  - swiglpk=5.0.3=py37hb718a55_0
  - tbb=2020.2=h4bd325d_4
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - cvxpy==1.1.18
    - ecos==2.0.8
    - future==0.18.2
    - metano==1.3.0
    - numpy==1.19.0
    - openopt==0.5629
    - osqp==0.6.2.post4
    - pymprog==1.0.0
    - qdldl==0.1.5.post0
    - scipy==1.7.3
    - scs==3.0.1
    - setproctitle==1.2.2
    - sortedcontainers==2.4.0

Then, we run the following command:

sbmlwriter.py -r rea_iPin571.txt -p sce_iPin571_WT-Alanine.txt -o output.txt

Input files (downloaded from here: https://mmtb.brenda-enzymes.org/models/view/12)
[rea_iPin571.txt](https://github.com/JKoblitz/metano/files/7808941/rea_iPin571.txt)
[sce_iPin571_WT-Alanine.txt](https://github.com/JKoblitz/metano/files/7808942/sce_iPin571_WT-Alanine.txt)

However, the result is as follows:

Start creating SBML file 'output.txt'..
Reaction file:           'rea_iPin571.txt'
Scenario file:           'sce_iPin571_WT-Alanine.txt'
Compartment reg-ex:      'None'
Default compartment:     'Cytosol'
Infinity value:          None
Info: The metabolic network has 692 reactions and 564 metabolites.
Traceback (most recent call last):
  File "/users/pmamirs/anaconda3/envs/metano/bin/sbmlwriter.py", line 8, in <module>
    sys.exit(main())
  File "/users/pmamirs/anaconda3/envs/metano/lib/python3.7/site-packages/metano/sbmlwriter.py", line 750, in main
    sbmlWriter.writeFile(options.outputFile)
  File "/users/pmamirs/anaconda3/envs/metano/lib/python3.7/site-packages/metano/sbmlwriter.py", line 346, in writeFile
    sbml.setAttribute(SbmlDef.LEVEL, "3")
  File "/users/pmamirs/anaconda3/envs/metano/lib/python3.7/xml/dom/minidom.py", line 741, in setAttribute
    attr.ownerDocument = self.ownerDocument
AttributeError: ownerDocument

We are not sure at this point if this is a version issue or an issue with the input format. The module xml.dom.minidom is built into python and we are not sure if there is a way to check different versions without changing the python version, which we have already done. We would appreciate any help on how to get the sbmlwriter.py script up and running.

Best,
Martin

[UPDATE]

We also tried the above command line (sbmlwriter.py -r rea_iPin571.txt -p sce_iPin571_WT-Alanine.txt -o output.txt) inside the metano docker container. It produced the same error as pasted above (using the input files I linked). We also tried sbmlwriter.py with the provided example data, but got the same error. However, when we ran the Phaeobacter model with the fba.py script inside the docker container, everything works fine.

So, it looks like that there is a problem with the sbmlwriter.py script, or a dependency issue. Again, we would really appreciate any help with our problem of converting the Phaeobacter model into a format that can be used outside the metano toolbox.

**Comment by JKoblitz** [comment]
Dear @martsper,

sorry for the late response. GitHub didn't think it was necessary to notify me. However, I found the source of your problem. Apparently minidom has changed something about their syntax. 
I have adjusted the sbmlwriter.py and released a new version: https://pypi.org/project/metano/1.3.1/
Updating should resolve your issue. I will leave this issue open for now, so come back to me if something happens again.

Cheers, Julia

**Comment by martsper** [comment]
Dear Julia,

that's great, thanks a lot for fixing it! I am looking forward to work on the model, and to further explore the metano toolbox.

Best,
Martin
